name: API Build with Allure Report

on:
  schedule:
    # Runs every day at 11 PM IST (which is 17:30 UTC)
    - cron: '30 17 * * *'

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Run Tests and Generate Allure Report
        run: ./gradlew clean test allureReport

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: build/allure-report
