name: Nightly API Build with Allure Report

on:
  schedule:
    - cron: '30 17 * * *'  # 11:00 PM IST = 5:30 PM UTC

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to Gradle
        run: chmod +x gradlew

      - name: Run Tests and Generate Allure Report
        run: ./gradlew clean test allureReport

      - name: Upload Allure Report
        uses: ./.github/actions/upload-artifact
        with:
          name: allure-report
          path: build/allure-report
